cripto_main.cc File Reference
#include <fstream>
#include <iostream>
#include <string>
#include `cripto.h`
Functions
int main (int argc, char *argv[])
Universidad de La Laguna Escuela Superior de Ingeniería y Tecnología Grado en Ingeniería Informática Informática Básica.
Function Documentation
main()
int main (int argc, char * argv[])
Universidad de La Laguna Escuela Superior de Ingeniería y Tecnología Grado en Ingeniería Informática Informática Básica.
Author
F. de Sande
Date
7.nov.2020 Cada nuevo término de la serie de Fibonacci se genera sumando los dos anteriores. Comenzando con 0 y 1, los primeros 10 términos serán: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34 Desarrolle en C++ un programa que calcule la suma de todos los términos de valor par de la serie que sean menores que 1000.
See also
https://docs.google.com/document/d/1-3hTIVf8tPrbn9u0vs0Cm2IGyX1XBgv8hReVU0KOSUQ/edit?usp=sharing
stoi http://www.cplusplus.com/reference/string/stoi/ An Object Oriented Version of the program:
https://stackoverflow.com/questions/21360694/sum-of-even-fibonacci-numbers-under-1000exit Main function
Parameters
in argc Number of command line parameters
in argv Vector containing (char*) the parameters
Definition at line 32 of file cripto_main.cc.
References DecryptCesar(), DecryptXor(), EncryptCesar(), EncryptXor(), IsFileOpen(), and Usage().
                                 {
  Usage(argc, argv);
  std::string input_file = argv[1];
  std::string output_file = argv[2];
  char method = argv[3][0];
  std::string password = argv[4];
  int key{0};
  char operation = argv[5][0];
  const int KconstNumber = 128;
  IsFileOpen(input_file);
  if (operation == '+') {
    if (method == '2') {
      key = std::stoi(password);
      EncryptCesar(input_file, output_file, key);
    } else if (method == '1') {
      EncryptXor(input_file, output_file, password, KconstNumber);
    }
  } else if (operation == '-') {
    if (method == '2') {
      key = std::stoi(password);
      DecryptCesar(input_file, output_file, key);
    } else if (method == '1') {
      DecryptXor(input_file, output_file, password, KconstNumber);
    }
  }
  return 0;
}