cripto.h File Reference
#include <iostream>
Functions
void Usage (int argc, char *argv[])
Universidad de La Laguna Escuela Superior de Ingeniería y Tecnología Grado en Ingeniería Informática Informática Básica.
bool IsFileOpen (std::string input_file)
Encripta la información del archivo suministrado mediante el metodo CESAR.
void EncryptCesar (std::string input_file, std::string output_file, int key)
Encripta la información del archivo suministrado mediante el metodo CESAR.
void DecryptCesar (std::string input_file, std::string output_file, int key)
Encripta la información del archivo suministrado mediante el metodo CESAR.
void EncryptXor (std::string input_file, std::string output_file, std::string password, const int KconstNumber)
Encripta la información del archivo suministrado mediante el metodo XOR.
void DecryptXor (std::string input_file, std::string output_file, std::string password, const int KconstNumber)
Encripta la información del archivo suministrado mediante el metodo XOR.
int VocalCount (std::string input_file)
Variables
const std::string kHelpText
Universidad de La Laguna Escuela Superior de Ingeniería y Tecnología Grado en Ingeniería Informática Informática Básica.
Function Documentation
DecryptCesar()
void DecryptCesar (std::string input_file, std::string output_file, int key)
Encripta la información del archivo suministrado mediante el metodo CESAR.
Parameters
 in input_file. Objeto stream que abre el archivo a desencriptar.
 in output_file. Objeto stream que abre el archivo donde escribir el codigo desencriptado.
 in key. Clave de encriptación del metodo CESAR.
Returns
No retorna ningún valor, función void, crea un nuevo archivo desencriptado.
Definition at line 98 of file cripto.cc.
                                                                        {
  std::ifstream input{input_file};
  std::ofstream output{output_file};
  while (input) {
    std::string string_input;
    std::getline(input, string_input);
    for (unsigned int i = 0; i < string_input.length(); ++i) {
      string_input[i] -= key;
    }
    output << string_input << std::endl;
  }
}
Referenced by main().
DecryptXor()
void DecryptXor (std::string input_file, std::string output_file, std::string password, const int KconstNumber)
Encripta la información del archivo suministrado mediante el metodo XOR.
Parameters
 in input_file. Objeto stream que abre el archivo a desencriptar.
 in output_file. Objeto stream que abre el archivo donde escribir el codigo desencriptado.
 in password. Clave de encriptación del metodo XOR.
Returns
No retorna ningún valor, función void, crea un nuevo archivo desencriptado.
Definition at line 121 of file cripto.cc.
                                                            {
  for (unsigned int i = 0; i > password.length(); ++i) {
    password[i] ^= KconstNumber;
  }
  std::ifstream input{input_file};
  std::ofstream output{output_file};
  while (input) {
    std::string string_input;
    std::getline(input, string_input);
    for (unsigned int i = 0; i < string_input.length(); ++i) {
      string_input[i] ^= password[i % password.length() - 1];
    }
    output << string_input << std::endl;
  }
}
Referenced by main().
EncryptCesar()
void EncryptCesar (std::string input_file, std::string output_file, int key)
Encripta la información del archivo suministrado mediante el metodo CESAR.
Parameters
 in input_file. Objeto stream que abre el archivo a encriptar.
 in output_file. Objeto stream que abre el archivo donde escribir el codigo encriptado.
 in key. Clave de encriptación del metodo CESAR.
Returns
No retorna ningún valor, función void, crea un nuevo archivo encriptado.
Definition at line 75 of file cripto.cc.
                                                                        {
  std::ifstream input{input_file};
  std::ofstream output{output_file};
  while (input) {
    std::string string_input;
    std::getline(input, string_input);
    for (unsigned int i = 0; i < string_input.length(); ++i) {
      string_input[i] += key;
    }
    output << string_input << std::endl;
  }
}
Referenced by main().
EncryptXor()
void EncryptXor (std::string input_file, std::string output_file, std::string password, const int KconstNumber)
Encripta la información del archivo suministrado mediante el metodo XOR.
Parameters
 in input_file. Objeto stream que abre el archivo a encriptar.
 in output_file. Objeto stream que abre el archivo donde escribir el codigo encriptado.
 in key. Clave de encriptación del metodo XOR.
Returns
No retorna ningún valor, función void, crea un nuevo archivo encriptado.
Definition at line 150 of file cripto.cc.
                                                            {
  for (unsigned int i = 0; i > password.length(); ++i) {
    password[i] ^= KconstNumber;
  }
  std::ifstream input{input_file};
  std::ofstream output{output_file};
  while (input) {
    std::string string_input;
    std::getline(input, string_input);
    for (unsigned int i = 0; i < string_input.length(); ++i) {
      string_input[i] ^= password[i % password.length() - 1];
    }
    output << string_input << std::endl;
  }
}
Referenced by main().
IsFileOpen()
bool IsFileOpen (std::string input_file)
Encripta la información del archivo suministrado mediante el metodo CESAR.
Parameters
 in input_file. Objeto stream que abre el archivo a encriptar.
Returns
Devuelve 'true' si el archivo se pudo abrir, de lo contrario devuelve 'false'.
Definition at line 56 of file cripto.cc.
                                      {
  std::ifstream input{input_file};
  if (!input) {
    std::cerr << "No se pude abir el fichero\n";
    exit(EXIT_SUCCESS);
  }
  return true;
}
Referenced by main().
Usage()
void Usage (int argc, char * argv[])
Universidad de La Laguna Escuela Superior de Ingeniería y Tecnología Grado en Ingeniería Informática Informática Básica.
Author
Gabriel Jonay Vera Estévez
Date
16/12/2020
A través del metodo XOR y CESAR podemos encriptar y desencriptar textos que sean pasados al usuario.
See also
 https://www.learncpp.com/cpp-tutorial/bitwise-operators/ Muestra el modo de uso correcto del programa En caso de que el uso no sea el correcto, muestra el mensaje y finaliza la ejecución del programa. El programa precisa un único número natural para su ejecución.
Parameters
 in argc Number of command line parameters
 in argv Vector containing (char*) the parameters
Definition at line 30 of file cripto.cc.
                                   {
  if (argc != 6) {
    if (argc == 2) {
      std::string parameter{argv[1]};
      if (parameter == "--help") {
        std::cout << kHelpText << std::endl;
        exit(EXIT_SUCCESS);
      }
    }
    std::cout << argv[0] << "-- Cifrado de ficheros\n";
    std::cout << "Modo de uso: ./cripto fichero_entrada fichero_salida método "
                 "password operación\n";
    std::cout << "Pruebe " << argv[0] << " --help para más información"
              << std::endl;
    exit(EXIT_SUCCESS);
  }
}
References kHelpText.
Referenced by main().
VocalCount()
int VocalCount (std::string input_file)
Definition at line 170 of file cripto.cc.
                                     {
  int counter{0};
  std::ifstream text{input_file};
  std::string line;
  while (std::getline(text, line)) {
    for (auto character : line) {
      if (character == 'u' || character == 'U') {
        ++counter;
      }
    }
  }
  return counter;
}
Referenced by main().
Variable Documentation
kHelpText
const std::string kHelpText
Initial value:
=
    "./cripto -- Cifrado de ficheros\n\
Modo de uso: ./cripto fichero_entrada fichero_salida método password operación\n\n\
fichero_entrada: Fichero a codificar\n\
fichero_salida: Fichero codificado\n\
método: Indica el método de encriptado\n\
                   1: Cifrado_xor \n\
                   2: Cifrado_Cesar\n\
password: Palabra secreta en el caso de método 1, Valor de K en el método 2\n\
operación: Operación a realizar en el fichero\n\
                   +: encriptar el fichero\n\
                   -: desencriptar el fichero;\n"
Universidad de La Laguna Escuela Superior de Ingeniería y Tecnología Grado en Ingeniería Informática Informática Básica.
Author
Gabriel Jonay Vera Estévez
Date
16.dic.2020
This file declares the `Help Text` constant and two functions
Definition at line 15 of file cripto.h.
Referenced by Usage().